name: Xiao Hui
motto: I'm going to succeed because I'm crazy enough to think I can.
github_username: hokix
title: Xiao Hui's Blog
email: hokix@live.com

# Build settings
exclude: ["vendor/", ".bundle/", "Gemfile", "Gemfile.lock", "node_modules/"]

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives
  - jekyll-redirect-from

# Pagination
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  sort_reverse: true

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Conversion
markdown: kramdown
highlighter: rouge

# Outputting
permalink: /:year/:month/:day/:title/
timezone: Asia/Shanghai

# Markdown Processors
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    auto_ids:       true
    footnote_nr:    1
    entity_output:  as_char
    toc_levels:     1..6
    smart_quotes:   lsquo,rsquo,ldquo,rdquo

# Sass/SCSS
sass:
  style: compressed
  quiet_deps: true

theme: jekyll-theme-cayman
