name: Xiao Hui
motto: I'm going to succeed because I'm crazy enough to think I can.
github_username: hokix
title: Xiao Hui's Blog
email: hokix@live.com

# Where things are
source:      .
destination: ./_site
layouts_dir:     ./_layouts
includes_dir: ./_includes

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      ["vendor/", ".bundle/", "Gemfile", "Gemfile.lock", "node_modules/"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives
  - jekyll-redirect-from

# Pagination
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  sort_reverse: true

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Conversion
markdown:    kramdown
highlighter: rouge
excerpt_separator: "\n\n"

# Serving
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Outputting
permalink:     /:year/:month/:day/:title/
paginate_path: /page:num
timezone: Asia/Shanghai

defaults: []

# Markdown Processors
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    auto_ids:       true
    footnote_nr:    1
    entity_output:  as_char
    toc_levels:     1..6
    smart_quotes:   lsquo,rsquo,ldquo,rdquo

# Sass/SCSS
sass:
  style: compressed

theme: jekyll-theme-cayman
